#!/bin/bash
# Set a value that we can use for a datestamp
DATE=`date +%Y-%m-%d`
# Our Base backup directory
BASEBACKUP="/mysql_backups/dbs"


for DATABASE in `cat /root/scripts/db-list.txt`
do
       # This is where we throw our backups.
       FILEDIR="$BASEBACKUP/$DATABASE"

       # Test to see if our backup directory exists.
       # If not, create it.
       if [ ! -d $FILEDIR ]
       then
               mkdir -p $FILEDIR
       fi

       echo -n "Exporting database:  $DATABASE"
       mysqldump --user=root --password="somepass"  --opt $DATABASE | gzip -c -9 > $FILEDIR/$DATABASE-$DATE.sql.gz
       echo "      ......[ Done ] "
done

# AutoPrune our backups.  This will find all files
# that are "MaxFileAge" days old and delete them.
MaxFileAge=7
find $BASEBACKUP -name '*.gz' -type f -mtime +$MaxFileAge -exec rm -f {} \;
